---
title: "Results Appendix"
output: pdf_document
---

### Additional simulation results for log-heterogeneity

Here, we detail results on the bias and accuracy of the marginal variance of the effect size distribution. Figure \@ref(fig:heterogeneity-bias) depicts the bias for the CHE, CML, and ARGL estimators of log-heterogeneity. Note that, for these graphs, we present the results for the CHE method instead of CHE-ISCW as the estimates of total heterogeneity are the same across the two methods. In most conditions, the estimators are biased in the negative direction. Bias is high for all three estimators in conditions where the between-study heterogeneity is low ($\tau = 0.05$) with bias improving as between-study heterogeneity increases. Bias of the CML estimator is closer to zero than that of CHE in conditions where there is strong selection. The ARGL estimator, particularly, has degrading bias especially in conditions where selection is strong, average SMD is low and between-study heterogeneity is low (the y axis cuts off at -2 and the bias of ARGL is lower than that). Figure \@ref(fig:heterogeneity-rmse) depicts the scaled RMSE for estimators of log-heterogeneity. Figures \@ref(fig:heterogeneity-rmse-ARGL-CHE) through \@ref(fig:heterogeneity-rmse-ARGL-CML) provide greater detail about the relative accuracy of the three methods. In most conditions, the CML estimator outperforms ARGL in terms of RMSE. The RMSE of CML is closer to zero than that of CHE especially in conditions where selection is strong, average SMD is low, between-study heterogeneity is large, and sample size is large.

### Selection Parameter

Here, we detail results on the bias, accuracy and coverage of the CML and ARGL estimators of the log-selection parameter in the step-function models. Figure \@ref(fig:selection-bias) shows that bias is similar for the two estimators. Both estimators show bias close to zero in conditions with low average SMD and high between-study heterogeneity but high negative bias in conditions with strong selection probability and high average SMD, particularly with low between-study heterogeneity. In conditions with high SMD, there may not be much selection occurring as non-significant effects are not as likely.<!--# does this go in discussion - the explanation of results? --> Figure \@ref(fig:selection-rmse) depicts the RMSE for the ARGL and CML estimators of the log-selection parameter with Figure \@ref(fig:selection-rmse-ARGL-CML) depicting a more detailed view of the relative accuracy of the ARGL versus the CML estimators. The CML estimator outperforms ARGL, especially in conditions with strong selection. Figures \@ref(fig:CML-zeta-coverage-full) and \@ref(fig:ARGL-zeta-coverage-full) depict the confidence interval coverage of the two estimators with various combinations of cluster bootstrapping methods and bootstrap confidence interval estimation approaches. None of the methods provide adequate coverage. <!--# write more or just leave this here? :D -->
