---
title: "Simulation Methods"
output: pdf_document
bibliography: references.bib
editor_options: 
  markdown: 
    wrap: sentence
---

We conducted a Monte Carlo simulation study to examine the performance of the PML and ARGL estimators for a step-function selection model with a single step, under a wide range of conditions where primary studies contribute multiple, statistically dependent effect size estimates.
We examine two distinct selection processes, including one where the probability of selection depends only on the $p$-value of the individual effect size estimate (i.e., univariate selection) and one in which the probability of selection is influenced by the significance of other outcomes in the same study (a form of multivariate selection).
We compared the performance of our novel estimators to two available alternatives: a summary meta-analysis that addresses the dependency structure but does not correct for selective reporting and the PET-PEESE adjustment.[@stanley2014meta]
We evaluated the estimators in terms of convergence rates, bias, accuracy, and CI coverage for recovering the average effect size prior to selective reporting.
To limit computational burden, we evaluated the performance of bootstrap CIs only for a subset of the conditions. 

We ran the simulation in R Version 4.4.1 [@rcoreteam] using the high-throughput computing cluster at the University of Wisconsin - Madison.[@CHTC]
The simulation code made use of several R packages, including `metafor` [@Viechtbauer2010conducting], `clubSandwich` [@clubSandwich], `simhelpers` [@simhelpers], `optimx` [@optimx], `nleqslv` [@nleqslv], and `tidyverse` [@tidyverse].

## Data generation

We simulated meta-analyses based on a CHE working model, with individual effect size estimates selected
for inclusion based on a generalization of the step-function selection model that encompasses both univariate and multivariate selection.
To generate each meta-analytic dataset, we sampled effective sample sizes[^ESS] and numbers of effects per study from an empirical distribution based on the What Works Clearinghouse database, where study $j$ had an effective sample size of $N_j$ and contributed $k_j^* \geq 1$ effect size estimates prior to selective reporting.
 We then generated $r_j$, an outcome correlation for study $j$, by drawing from a beta distribution with mean $\rho$ and standard deviation 0.05. 
This approach produces a plausible dependence structure in which all within-study correlations are positive, as when multiple outcomes measure the same underlying construct or the same construct at different time points. 
For simplicity, we assumed a constant correlation between pairs of outcomes within a primary study but allowed the correlation to vary slightly from study to study.

[^ESS]: For studies that involved cluster-level treatment assignment, we computed effective sample sizes that account for the nesting of observations within clusters rather than using the raw participant-level sample sizes.

We then simulated raw outcomes for each primary study. 
To do so, we first generated an average effect size per study, $\delta_j$, from a normal distribution with mean $\mu$ and variance
of $\tau_B^2$. 
Given $\delta_j$, we generated $k_j^*$ effect size parameters per study, $\bs\delta_j = \left(\delta_{1j},...,\delta_{k_j^* j}\right)'$, drawing $\delta_{ij}$ from a normal distribution with mean of $\delta_j$ and variance of $\omega^2$.
We generated two-arm group comparisons with $N_j / 2$ participants per group groups, with individual outcome vectors simulated from multivariate normal distributions as
$$
\mat{Y}_{hj}^T \sim N(\bs\delta_j, \boldsymbol\Psi_j) \qquad \text{and} \qquad
\mat{Y}_{hj}^C \sim N(\mat{0}, \boldsymbol\Psi_j).
$$
Here, $\mat{Y}_{hj}^T$ and $\mat{Y}_{hj}^C$ are
$k_j^* \times 1$ vectors of outcomes for participant $h$ in the treatment or control group of study $j$ and $\boldsymbol\Psi_j$ is the covariance matrix for outcomes in study $j$, with the diagonal elements equal to 1 and off-diagonal elements equal to $r_j$.[^psi-structure]
From the raw outcome data, we calculated standardized mean differences using Hedges's $g$ bias correction for each of the correlated outcomes, yielding effect size estimates $y^*_{ij}$ for $i=1,...,k_j^*$ and $j = 1,...,J^*$.
We calculated the sampling variances using conventional formulas [@borenstein2019effect] and computed one-sided $p$-values based on two-sample $t$-tests for the null of $H_0: \delta_{ij} \leq 0$.

[^psi-structure]: The structure of $\boldsymbol\Psi_j$ is plausible for meta-analyses with dependent effects and simplifies the data-generating process. The assumption of a unit sampling variance is a standard practice when simulating data for standardized effect sizes like Hedges's $g$ because it does not affect the distribution of generated effect size estimates.

After simulating results for study $j$, we applied a generalized step-function selection model to the individual effect size estimates, with a one-sided selection
threshold at $\alpha_1 = 0.025$. 
Under the generalized model, the probability that a given effect is reported still depends on whether it is affirmative (i.e., statistically significant and in the expected direction), but it may also depend on the number of other affirmative results in the same study.
Let $s_{ij}$ be an indicator equal to 1 if effect $i$ in study $j$ is affirmative, $s_{ij} = I(p_{ij} < .025)$, and
denote the number of affirmative effect size estimates in study $j$ as $k^A_j = \sum_{i=1}^{k_j} s_{ij}$.
We assume that effect size estimate $i$ in study $j$ is observed with probability 
\begin{equation}
\label{eq:generalized-selection}
\pi_{ij} = s_{ij} + (1 - s_{ij}) \times \lambda_1^{(k^A_j - 1)^\psi},
\end{equation}
for $\psi \geq 0$. 
When $\psi = 0$, the probability that a non-affirmative result is reported depends only on its own $p$-value, so the selection process is univariate.
When $\psi > 0$, the probability that a non-affirmative result is reported is affected by the number of affirmative results within the same study, with more affirmative results leading to a higher probability that a non-affirmative result will also be reported---a form of multivariate selection.
Under the multivariate process, $\lambda_1$ can be interpreted as the probability that a non-affirmative result is reported when there are no affirmative findings in the study (i.e., when $k^A_j = 0$).

We repeated the process of generating studies until the database included a total of $J$ studies with at least one observed result, where observed study $j$ includes $k_j$ effect size estimates for $1 \leq k_j \leq k_j^*$.

## Estimation methods

We estimated step-function selection models with a single step at $\alpha_1 = 0.025$, so that the assumed marginal selection process is aligned with the actual selective reporting process when $\psi = 0$.
We estimated PML and ARGL estimators and calculated cluster-robust CIs as described in Section \@ref(estimation-methods).
For comparison purposes, we also computed model-based confidence intervals constructed using the inverse Hessian matrix of the PML estimator, which do not account for the dependence structure of the data; therefore, we expect that they would have coverage levels below the nominal level.
For a subset of simulation conditions, we examined percentile, basic, studentized, and bias-corrected-and-accelerated bootstrap CIs based on the non-parametric two-stage bootstrap, clustered bootstrap, and fractional random weight bootstrap as described in `r appendix_prefix` \@ref(bootstrap-details).

We compared the step-function PML and ARGL estimators to two alternative methods.
First, we estimated a summary meta-analysis model without any correction for selective reporting, using the CHE-ISCW working model to account for effect size dependency.[@chen2024adapting]
We estimated the variance components using restricted maximum likelihood and assumed a sampling correlation of 0.8 for all pairs of effect size estimates from the same study, which leads to a degree of mis-specification when the average correlation used in the data-generating process differs from 0.80.
This assumption aligns with the default correlation structure used by `robumeta` [@robumeta], a widely used R package for meta-analysis with RVE.
Second, we implemented a variation of the PET/PEESE estimator, adapted to accommodate dependent effect sizes.[^PET-PEESE]
We combined the estimators by using PEESE if the PET estimator is statistically distinct from zero at an $\alpha$-level of 0.10, and otherwise using PET.[@stanley2014meta]
For the PET/PEESE and CHE-ISCW estimators, we calculated CIs using cluster-robust variance estimation with the CR2 small-sample correction and Satterthwaite degrees of freedom.[@chen2024adapting]

[^ISCW]: CHE-ISCW is based on the working model 
  \begin{equation}
  \label{eq:che}
  y_{ij} = \mu + u_j + v_{ij} + e_{ij},
  \end{equation}
  where $u_j \sim N(0, \tau^2)$, $v_{ij} \sim N(0, \omega^2)$, $e_{ij} \sim N(0, \sigma_{ij}^2)$, and $\cor(e_{hj},e_{ij}) = \rho$, with the sampling variances treated as known and assuming a common correlation between sampling errors within the same study. 
  Rather than estimating $\mu$ using weights based on the full working model, CHE-ISCW instead uses generalized least squares with weighting matrices that are the inverse of the variance-covariance matrix of the sampling errors $e_{1j},...,e_{k_j j}$ only. 
  This has the effect of allocating more weight to studies with smaller sampling variances, providing some robustness to selective reporting of study results.

[^PET-PEESE]: The PET estimator is based on the working model \begin{equation}
  \label{eq:pet}
  T_{ij} = \mu + \beta \times \frac{2}{\sqrt{N_j}} + e_{ij}
  \end{equation} 
  The PEESE estimator is similar, but uses the sampling variance instead of the sampling standard error: \begin{equation}
  \label{eq:peese}
  T_{ij} = \mu + \beta \times \frac{4}{N_j} + e_{ij}
  \end{equation} 
  We use functions of the sample size ($N_j$) in place of the standard error or variance. This approach addresses the fact that for many effect size metrics, such as Hedges’ $g$, the sampling variance is functionally related to the effect size estimate itself, which introduces artificial correlation between the estimates and their standard errors.[@pustejovsky2019testing] 
  For both estimating equations, sampling errors are assumed to have fixed variances $\Var(e_{ij}) = \sigma_{ij}^2$ and constant sampling correlation within studies, $\cor(e_{hj},e_{ij} )=\rho$.[@chen2024adapting]


## Experimental design

Table \@ref(tab:sim-design) summarizes the experimental design for this study. 
Manipulated parameters included the number of observed studies ($J$), primary study sample size distribution, overall average standardized mean difference
($\mu$), between-study heterogeneity ($\tau_B$), within-study heterogeneity ratio
($\omega^2 / \tau_B^2$), average correlation between outcomes ($\rho$),
dependence of the selection process ($\psi$), and
probability of selection for non-affirmative results ($\lambda_1$). 

We examined a wide range of conditions for the number of primary studies included in the meta-analysis, ranging from relatively small databases of $J = 15$ to very large databases with $J = 120$ studies. 
We chose these values to cover the conditions found in real meta-analyses of education and psychology research.[@Pellegrini2025exploring; @Wu2025what]

We manipulated the primary study sample size while varying the number of effect sizes per study ($k_j$) based on an empirical distribution. 
For the typical primary study sample sizes, we used the empirical distribution of effective sample sizes in the What Works Clearinghouse database of findings from educational intervention studies.
These sample sizes ranged from 37 to 2,295 with a median of 211. 
Within these conditions, we also drew $k_j$ from the same database, where the number of effect sizes per study ranged from 1 to 48 with a median of 3. 
To explore the influence of the effective sample size distribution, we also ran conditions in which we divided the sample
sizes from the What Works Clearinghouse database by three to represent primary studies with smaller sample sizes,
such as those used in psychology laboratory studies.

We examined values for the overall average SMD ($\mu$) ranging from 0.0 to 0.80, which covers the range of effects observed in a review of 747 randomized control trials of education interventions.[@kraft2020interpreting]
We used values of $\tau$ ranging from 0.05 (a small degree of heterogeneity) to 0.45 (a large degree of heterogeneity). 
We specified the degree of within-study heterogeneity in relative terms, by setting the ratio of $\omega^2$ to between-study heterogeneity $\tau^2$ at either 0 (i.e., no within-study heterogeneity) or 0.5. 
For the average correlation between outcomes from the same study, we examined the values of 0.40 or 0.80. The default value of the average
correlation in software packages that implement RVE is 0.80. 
Thus, in conditions where $\rho$ is 0.80, the working model used in CHE-ISCW and PET/PEESE is approximately correctly specified. 
We included conditions where $\rho = 0.4$ to examine performance when this working model is not correctly specified. 

```{r sim-design, tab.cap="Simulation design parameters"}
library(kableExtra)
library(tidyverse)

design_dat <- tibble(
  Parameter = c(
    "Number of observed studies ($J$)",
    "Primary study sample size",
    "Overall average SMD ($\\mu$)",
    "Between-study heterogeneity ($\\tau_B$)",
    "Heterogeneity ratio ($\\omega^2 / \\tau_B^2$)",
    "Average correlation between outcomes ($\\rho$)",
    "Dependence of the selection process ($\\psi$)",
    "Probability of selection for non-affirmative effects ($\\lambda_1$)"
  ),
  `Full Simulation` = c(
    "15, 30, 60, 90, 120",
    "Typical, Small",
    "0.0, 0.2, 0.4, 0.8",
    "0.05, 0.15, 0.30, 0.45",
    "0.0, 0.5",
    "0.40, 0.80",
    "0, 1",
    "0.02, 0.05, 0.10, 0.20, 0.50, 1.0"
  ),
  `Bootstrap Simulation` = c(
    "15, 30, 60",
    "Typical, Small",
    "0.0, 0.2, 0.4, 0.8",
    "0.15, 0.30, 0.45",
    "0.0, 0.5",
    "0.80",
    "0, 1",
    "0.05, 0.20, 1.0"
  )
)

kable(
  design_dat, 
  caption = "Parameter values examined in the simulation study",
  booktabs = TRUE, 
  escape = FALSE,
  position = "tb"
) |>
  kable_styling() |>
  column_spec(1, width = "2.5in")
  
design_dat_expanded <- 
  design_dat %>%
  mutate(
    levels_full = map_int(str_split(`Full Simulation`, ", "), length),
    levels_boot = map_int(str_split(`Bootstrap Simulation`, ", "), length)
  )


```

We considered two conditions for the selective reporting process. First, we examined conditions with $\psi = 0$ so that the selection process was univariate, depending only on the one-sided $p$-value of each effect.
Second, we examined conditions with $\psi = 1$, a multivariate selection process where the selection probability for a non-affirmative result depends on the number of affirmative results obtained in the same study.
For both processes, we examined a wide range of values for the base probability of selection for non-affirmative effect sizes, ranging from no selective reporting ($\lambda_1 = 1$) to very severe selective reporting $(\lambda_1 = 0.02)$.

Parameters were fully crossed for a total of $`r paste(design_dat_expanded$levels_full, collapse = " \\times ")` = `r formatC(prod(design_dat_expanded$levels_full), big.mark = ",")`$ conditions in the full simulation study. 
Due to the computational demands of bootstrapping, we focused the bootstrap simulations on conditions with fewer studies per meta-analysis, for which we expected large-sample cluster-robust CIs to be relatively less effective.
We also reduced the number of parameter values for factors where we did
not observe much variation in results in the full simulation
(e.g., excluding $\tau = 0.30$). 
This resulted in $`r paste(design_dat_expanded$levels_boot, collapse = " \\times ")` = `r formatC(prod(design_dat_expanded$levels_boot), big.mark = ",")`$ conditions for the bootstrap simulations. 
For each condition, we generated 2,400 replications. 
This number of replications was chosen to ensure adequate precision; specifically, with 2,400 replications, the expected Monte Carlo standard error for a 95% confidence interval coverage rate is approximately 0.004, and even in the most conservative case (coverage of 50%), the standard error remains below 0.01.

## Performance criteria

We evaluated the performance of these methods in terms of convergence rates, bias,
root mean-squared error (RMSE), and 95% confidence interval coverage for the overall average effect size $\mu$.
The PML estimator did not converge for every replication.
To compute performance measures for this estimator, we substituted results for the ARGL estimator for replications where the PML estimator did not converge, so that performance of all methods was measured across the same set of replications.[@Pawel2025handling]

For confidence intervals based on cluster-robust variance estimation, we calculated coverage rates as the proportion of simulated intervals that included the true parameter. 
For bootstrap CIs, estimation of coverage rates is complicated by the fact that coverage is affected by the number of bootstrap replications. 
To mitigate computational demand, we used $B = 299$ although this is far fewer bootstraps per replication than recommended for analysis of real data. 
To estimate coverage rates for confidence intervals as would be used in practice, we used an extrapolation technique.[@boos2000montecarlo]
For each replication, we computed bootstrap confidence intervals not only for $B = 299$, but also for $B = 49$, 99, and 199 bootstraps, randomly selected without replacement.
We computed coverage rates separately for each value of $B$, fit a linear regression of the coverage rate on $1 / B$, and then used this regression to predict the coverage rate of confidence intervals based on $B = 1999$ bootstraps.
`r appendix_prefix` \@ref(bootstrap-extrapolation) provides further details and demonstrates the performance of the extrapolation technique.
