---
title             : "Estimation and inference for step-function selection models in meta-analysis with dependent effects"
shorttitle        : "Step-function selection models"

author: 
  - name          : "James E. Pustejovsky"
    corresponding : yes    # Define only one corresponding author
    affiliation   : "1"
    address       : "1082C Educational Sciences, 1025 W Johnson St. Madison, WI 53706-1706"
    email         : "pustejovsky@wisc.edu"
  - name          : "Martyna Citkowicz"
    affiliation   : "2"
    address       : "Address"
    email         : "mcitkowicz@air.org"
  - name          : "Megha Joshi"
    affiliation   : "2"
    address       : "Address"
    email         : "megha.j456@gmail.com"
    
affiliation:
  - id            : "1"
    institution   : "University of Wisconsin-Madison"
  - id            : "2"
    institution   : "American Institutes for Research"

note              : "\\ \\newline `r format(Sys.Date(), '%B %d, %Y')`"

abstract: |
  Meta-analyses in social science fields face multiple methodological challenges arising from how primary research studies are designed and reported. One challenge is that many primary studies report multiple relevant effect size estimates. Another is selective reporting bias, which arises when the availability of study findings is influenced by the statistical significance of results. Although many selective reporting diagnostics and bias-correction methods have been proposed, few are suitable for meta-analyses involving dependent effect sizes. Among available methods, step-function selection models are conceptually appealing and have shown promise in previous simulations. We study methods for estimating step-function models from data involving dependent effect sizes, focusing specifically on estimating parameters of the marginal distribution of effect sizes and accounting for dependence using cluster-robust variance estimation or bootstrap resampling. We describe two estimation strategies, demonstrate them by re-analyzing data from a synthesis on ego depletion effects, and evaluate their performance through an extensive simulation study under single-step selection. Simulation findings indicate that selection models provide low-bias estimates of average effect size and that clustered bootstrap confidence intervals provide acceptable coverage levels. However, adjusting for selective reporting bias using step-function models involves a bias-variance trade-off, and unadjusted estimates of average effect sizes may be preferable if the strength of selective reporting is mild.
  
keywords          : "meta-analysis; dependent effect sizes; selection models; selective reporting; publication bias"

bibliography      : references.bib

figsintext        : yes
figurelist        : no
floatsintext      : yes 
tablelist         : no
footnotelist      : no
lineno            : no
mask              : no
numbersections    : yes
keep_tex          : yes
lang              : "en-US"
documentclass     : "apa7"
classoption       : "man, donotrepeattitle"
output            : 
  papaja::apa6_pdf
csl               : american-medical-association.csl
replace_ampersands: yes

header-includes:
- \usepackage{booktabs}
- \usepackage{multirow}
- \usepackage{multicol}
- \usepackage{amsthm}
- \newtheorem{thm}{Theorem}
- \newtheorem{lem}{Lemma}
- \usepackage{amsfonts}
- \usepackage{caption}
- \usepackage{multirow}
- \usepackage{float}
- \usepackage{subfig}
- \usepackage{longtable}
- \usepackage[figuresright]{rotating}
- \geometry{twoside=false, top=1in, bottom=1in, left=1in, right=1in}
- \usepackage{hyperref}
- \hypersetup{hidelinks}
- \raggedbottom
- \usepackage{setspace}
- \AtBeginEnvironment{tabular}{\singlespacing}
- \renewcommand*{\thesection}{Appendix \Alph{section}}
- \numberwithin{table}{section}
- \renewcommand\thetable{\Alph{section}\arabic{table}}
- \numberwithin{equation}{section}
- \renewcommand\theequation{\Alph{section}\arabic{equation}}
- \usepackage{xr}
- \externaldocument{step-function-selection-models-with-dependent-effects}
- \newcommand{\Prob}{\text{Pr}}
- \newcommand{\E}{\text{E}}
- \newcommand{\Cov}{\text{Cov}}
- \newcommand{\cor}{\text{cor}}
- \newcommand{\Var}{\text{Var}}
- \newcommand{\diag}{\text{diag}}
- \newcommand{\mat}[1]{\mathbf{#1}}
- \newcommand{\bs}{\boldsymbol}
- \newcommand{\trace}{\text{tr}}

---

```{r setup, include = FALSE}
library(knitr)
library(papaja)
library(metaselection)
library(tidyverse)

options(tinytex.verbose = TRUE)

opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(tinytex.clean = FALSE, knitr.kable.NA = '')
```

```{r child = "appendix-CML-derivatives.Rmd"}
```

```{r child = "appendix-ARGL-derivatives.Rmd"}
```

```{r child = "appendix-bootstrap-details.Rmd"}
```

```{r child = "appendix-simulation-results.Rmd"}
```

# References {-}

\begingroup
\setlength{\parindent}{-0.5in}
<div id="refs" custom-style="Bibliography"></div>
\endgroup

# (APPENDIX) Appendix {-}

