---
title             : "Estimating beta-function selection models in meta-analysis with dependent effects"
shorttitle        : "beta-function selection models"

author: 
  - name          : "Martyna Citkowicz"
    corresponding : yes    # Define only one corresponding author
    affiliation   : "1"
    address       : "1400 Crystal Drive, 10th floor Arlington, VA 22202-3289"
    email         : "mcitkowicz@air.org"
  - name          : "James E. Pustejovsky"
    affiliation   : "2"
    address       : "1082C Educational Sciences, 1025 W Johnson St. Madison, WI 53706-1706"
    email         : "pustejovsky@wisc.edu"
  - name          : "Megha Joshi"
    affiliation   : "2"
    address       : "Address"
    email         : "megha.j456@gmail.com"
affiliation:
  - id            : "1"
    institution   : "American Institutes for Research"
  - id            : "2"
    institution   : "University of Wisconsin-Madison"
  - id            : "3"
    institution   : "Progressive Insurance"

note              : "\\ \\newline `r format(Sys.Date(), '%B %d, %Y')`"

authornote: |
  Martyna Citkowicz, American Institutes for Research. 
  James E. Pustejovsky, Department of Educational Psychology, University of Wisconsin-Madison. 
  Megha Joshi, American Institutes for Research. 
  
  This work was presented at the 2025 conference of the Society for Research on Educational Effectiveness in Chicago, IL.
  
  R code and data for replicating the empirical example and the Monte Carlo simulation study are available on the Open Science Framework at https://osf.io/xehgq/overview?view_only=f5d031326aeb40daa7b16b3b9cee5a46.
  
  Funding: This work was supported, in part, by the Institute of Educational Sciences, U.S. Department of Education through grant R305D220026 to the American Institutes of Research. The opinions expressed are those of the authors and do not represent the views of the Institute of the U.S. Department of Education.

  Conflicts of Interest: The author(s) declared that there were no conflicts of interest with respect to the authorship or the publication of this article.

abstract: |
  Meta-analysts seek to draw generalizable inferences by pooling findings across available studies. Such efforts are hampered by selective reporting of study findings, which distorts meta-analytic inferences when statistically significant results are reported preferentially. Many techniques are available for investigating selective reporting in meta-analyses of independent effects, but psychological meta-analyses routinely involve dependent data structures, as arise when primary studies report results for multiple outcomes. Recent methodological developments that can accommodate dependent effects have focused on step-function selection models, in which the probability of reporting depends on whether a finding's p-value falls above or below pre-specified thresholds. We propose an alternative model in which the reporting probability follows a flexible, truncated beta function, avoiding the need to specify a priori  thresholds. Estimation of the model accommodates dependent effect sizes using cluster-robust variance estimation or clustered bootstrapping. We demonstrate the proposed approach by re-analyzing a published meta-analysis. Through an extensive simulation study, we evaluate the performance of the truncated beta model versus standard meta-analytic methods and versus step-function models to assess robustness to selection function misspecification. Results show that the beta-density model yields negligible bias across diverse conditions and outperforms standard alternatives when selective reporting is present, although simpler step-function models can be more precise under mild selection. Clustered bootstrap confidence intervals provide superior coverage compared to cluster-robust variance estimation. Although conventional methods remain more precise when selection is absent, the truncated beta selection model serves as a useful tool for sensitivity analysis and estimation in larger dataset that include dependent effects.
  
keywords          : "meta-analysis; dependent effect sizes; selection models; selective reporting; publication bias"

bibliography      : references.bib

figsintext        : yes
figurelist        : no
floatsintext      : yes
tablelist         : no
footnotelist      : no
lineno            : no
mask              : no
numbersections    : no
keep_tex          : yes
lang              : "en-US"
documentclass     : "apa7"
classoption       : "man, donotrepeattitle"
output            : 
  papaja::apa6_pdf
replace_ampersands: yes

header-includes:
- \usepackage{booktabs}
- \usepackage{multirow}
- \usepackage{multicol}
- \usepackage{amsthm}
- \newtheorem{thm}{Theorem}
- \newtheorem{lem}{Lemma} 
- \usepackage{amsfonts}
- \usepackage{caption}
- \usepackage{multirow}
- \usepackage{float}
- \usepackage{subfig}
- \usepackage{longtable}
- \usepackage[figuresright]{rotating}
- \geometry{twoside=false, top=1in, bottom=1in, left=1in, right=1in}
- \usepackage{hyperref}
- \hypersetup{hidelinks}
- \raggedbottom
- \usepackage{setspace}
- \AtBeginEnvironment{tabular}{\singlespacing}
- \usepackage{xr}
- \newcommand{\Prob}{\text{Pr}}
- \newcommand{\E}{\text{E}}
- \newcommand{\Cov}{\text{Cov}}
- \newcommand{\cor}{\text{cor}}
- \newcommand{\Var}{\text{Var}}
- \newcommand{\diag}{\text{diag}}
- \newcommand{\mat}[1]{\mathbf{#1}}
- \newcommand{\bs}{\boldsymbol}
- \newcommand{\trace}{\text{tr}}

---

```{r setup, include = FALSE}
library(knitr)
library(papaja)
library(metaselection)
library(tidyverse)
library(CRediTas)

options(tinytex.verbose = TRUE)

opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(tinytex.clean = FALSE, knitr.kable.NA = '')

appendix_prefix <- "Appendix"
```

# Estimating beta-function selection models in meta-analysis with dependent effects {#introduction}

```{r child = "introduction.Rmd"}
```

# Models and Estimation Methods {#model-and-estimation}

```{r child = "model-and-estimation-methods.Rmd"}
```

# Empirical Example {#empirical-example}

```{r child = "empirical-example.Rmd"}
```

# Simulation Methods {#simulation-methods}

```{r child = "simulation-methods.Rmd"}
```

# Simulation Results {#simulation-results}

```{r child = "simulation-results.Rmd"}
```

# Discussion {#discussion}

```{r child = "discussion.Rmd"}
```

# References {-}

\begingroup

<div id="refs" custom-style="Bibliography"></div>
\endgroup

# (APPENDIX) Appendix {-}

```{r child = "appendix-priors.Rmd"}
```

```{r child = "appendix-CRVE.Rmd"}
```

```{r child = "appendix-simulation-results.Rmd"}
```

